serviceAccount:
  create: false
  name: ${service_account}

cloudWatch:
  enabled: false

cloudWatchLogs:
  enabled: true
  region: ${aws_region}
  # logGroupName is a fallback to failed parsing
  logGroupName: /aws/eks/observability-accelerator/workloads
  logGroupTemplate: /aws/eks/observability-accelerator/${cluster_name}/$kubernetes['namespace_name']
  logStreamTemplate: $kubernetes['container_name'].$kubernetes['pod_name']
  log_key: log
  logRetentionDays: ${log_retention_days}
