
awsRegion: ${aws_region}
clusterName: ${cluster_name}


adotCollector:
  daemonSet:
    serviceAccount:
      create: false
      name: ${service_account}
    createNamespace: false
    extensions:
      sigv4auth:
        region: ${aws_region}
    service:
      metrics:
        receivers: ${service_receivers}
        exporters: ${service_exporters}
  sidecar:
    regionS3: ${aws_region}
