{
 "title": "AMP Accelerator Dashboard",
 "description": "Dashboard for Amazon Managed Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WorkspaceID",
    "query": "dimension_values(default,AWS/Prometheus,RuleEvaluations,Workspace)"
   },
   { "name": "datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# Ingestion Usage Metrics\n\nMetrics relating to ingestion usage of the AMP service"
   }
  },
  {
   "title": "Active Series Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expression": "SELECT SUM(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'ActiveSeries' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Workspace Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "expression": "SELECT AVG(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'IngestionRate' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Billing",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": {
    "content": "# Billing\n\nContains information relating to the cost of AMP\n\n"
   }
  },
  {
   "title": "Sum of Estimated AMP Charges (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 7 },
   "targets": [
    {
     "expression": "SELECT SUM(EstimatedCharges) FROM SCHEMA(\"AWS/Billing\", Currency,ServiceName) WHERE ServiceName = 'AmazonPrometheus'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "options": {
    "content": "# Alert Usage Metrics\n\nMetrics associated with Alertmanager Alert Usage"
   }
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'ActiveAlerts' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Alert Manager Notifications Failed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(AlertManagerNotificationsFailed) FROM SCHEMA(\"AWS/Prometheus\", Workspace) WHERE Workspace = '$WorkspaceID'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Alert Manager Alerts Received",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(AlertManagerAlertsReceived) FROM SCHEMA(\"AWS/Prometheus\", Workspace) WHERE Workspace = '$WorkspaceID'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Size of Alerts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SELECT AVG(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'SizeOfAlerts' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "AMP Logs",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "options": {
    "content": "# AMP Vended Logs\n\nLast 25 log events from AMP Vended Logs for alert and rule evaluation"
   }
  },
  {
   "title": "AMP Vended Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 24 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| limit 25",
     "logGroupNames": [ "/aws/vendedlogs/amp" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  }
 ]
}