{{- range .Values.clusterIssuers }}
{{- if eq .type "CA" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .name }}
  secretName: {{ .secretName }}
  {{- with .privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .issuer }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
