{{- range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  {{- if eq .type "selfSigned" }}
  selfSigned: {}
  {{- else if eq .type "CA" }}
  ca:
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}
