ampurl: ${amp_url}
region: ${region}
ekscluster: ${eks_cluster}
accountId: ${account_id}

assumeRoleArn: ${managed_prometheus_cross_account_role}

globalScrapeTimeout: ${global_scrape_timeout}
globalScrapeSampleLimit: ${global_scrape_sample_limit}

enableAPIserver: ${enable_apiserver_monitoring}

enableTracing: ${enable_tracing}
otlpGrpcEndpoint: ${otlp_grpc_endpoint}
otlpHttpEndpoint: ${otlp_http_endpoint}
tracingTimeout: ${tracing_timeout}
tracingSendBatchSize: ${tracing_send_batch_size}

enableCustomMetrics: ${enable_custom_metrics}
customMetrics: ${custom_metrics}

enableJava: ${enable_java}
javaScrapeSampleLimit: ${java_scrape_sample_limit}
javaPrometheusMetricsEndpoint: ${java_prometheus_metrics_endpoint}

enableNginx: ${enable_nginx}
nginxScrapeSampleLimit: ${nginx_scrape_sample_limit}
nginxPrometheusMetricsEndpoint: ${nginx_prometheus_metrics_endpoint}

enableIstio: ${enable_istio}
istioScrapeSampleLimit: ${istio_scrape_sample_limit}
istioPrometheusMetricsEndpoint: ${istio_prometheus_metrics_endpoint}

adotLoglevel: ${adot_loglevel}
adotServiceTelemetryLoglevel: ${adot_service_telemetry_loglevel}

enableAdotcollectorMetrics: ${enable_adotcollector_metrics}

serviceAccount: ${service_account}
namespace: ${namespace}
