{
 "title": "Amazon Observability Accelerator - HAProxy Ingress",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "All Status Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{instance=\"$host\"} == 1)",
     "legendFormat": "Front Up"
    },
    {
     "expr": "count(haproxy_backend_status{instance=\"$host\"} ==1)",
     "legendFormat": "Back Up"
    }
   ]
  },
  {
   "title": "Current Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{proxy=~\"$frontend\",instance=\"$host\"}) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{proxy=~\"$frontend\",instance=\"$host\"}) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Frontend - HTTP Request Total / Error / Denied",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Requests Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Requests Errors"
    }
   ]
  },
  {
   "title": "Total Number of connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back errors"
    },
    {
     "expr": "sum(rate(haproxy_backend_connections_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Frontend - HTTP Responses Rate per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }}"
    }
   ]
  },
  {
   "title": "Backend - HTTP Responses Rate per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "- back / + front" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Back {{ code }}"
    }
   ]
  },
  {
   "title": "Front - Incoming / Outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT {{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Incoming / Outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "IN {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "OUT {{ proxy }}"
    }
   ]
  }
 ]
}