{
 "title": "Kubernetes / Compute Resources / Cluster (Zeus)",
 "tags": [
  "infrastructure",
  "zeus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace))) / sum(kube_node_status_allocatable{\"@resource.service.name\"=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (namespace))) / sum(kube_node_status_allocatable{\"@resource.service.name\"=\"kube-state-metrics\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum((node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes{\"@resource.service.name\"=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace))) / sum(kube_node_status_allocatable{\"@resource.service.name\"=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (namespace))) / sum(kube_node_status_allocatable{\"@resource.service.name\"=\"kube-state-metrics\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (namespace, pod, container, node))) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{\"@resource.service.name\"=\"kube-state-metrics\"}) by (namespace)"
    },
    {
     "expr": "count(avg((max(kube_pod_owner{owner_kind=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (namespace, workload, pod, workload_type))) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (namespace, pod, container, node))) by (namespace)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace))) by (namespace)"
    },
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (namespace, pod, container, node))) by (namespace) / sum((sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (namespace))) by (namespace)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (namespace))) by (namespace)"
    },
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (namespace, pod, container, node))) by (namespace) / sum((sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (namespace))) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{\"@resource.service.name\"=\"kubelet\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{\"@resource.service.name\"=\"kube-state-metrics\"}) by (namespace)"
    },
    {
     "expr": "count(avg((max(kube_pod_owner{owner_kind=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (namespace, workload, pod, workload_type))) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{\"@resource.service.name\"=\"kubelet\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace))) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{\"@resource.service.name\"=\"kubelet\", container!=\"\"}) by (namespace) / sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (namespace))) by (namespace)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (namespace))) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{\"@resource.service.name\"=\"kubelet\", container!=\"\"}) by (namespace) / sum((sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (namespace))) by (namespace)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__interval])) by (namespace)"
    }
   ]
  },
  {
   "title": "Bandwidth by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{\"@resource.service.name\"=\"kubelet\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(namespace) (rate(container_fs_reads_total{\"@resource.service.name\"=\"kubelet\", container!=\"\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{\"@resource.service.name\"=\"kubelet\", container!=\"\", namespace!=\"\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{\"@resource.service.name\"=\"kubelet\", container!=\"\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{\"@resource.service.name\"=\"kubelet\", container!=\"\", namespace!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_writes_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_writes_bytes_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{\"@resource.service.name\"=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}