apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot
spec:
  image: public.ecr.aws/aws-observability/aws-otel-collector:latest
  mode: deployment
  serviceAccount: adot-collector-nginx
  config: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
          scrape_configs:
          - job_name: 'kubernetes-pod-nginx'
            static_configs:
              - targets: ['my-nginx-ingress-nginx-controller-metrics.nginx-ingress-sample.svc.cluster.local:10254']
    exporters:
      prometheusremotewrite:
        endpoint: {{ .Values.ampurl }}
        auth:
          authenticator: sigv4auth
      logging:
          loglevel: debug
    extensions:
      sigv4auth:
        region: {{ .Values.region }}
        service: "aps"
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    service:
      extensions: [pprof, zpages, health_check, sigv4auth]
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [logging, prometheusremotewrite]
