name: Check Markdown links

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"

  pull_request:
    branches:
      - main
    paths:
      - "**/*.md"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install markdown-link-check
        run: npm install -g markdown-link-check@3.10.2
      - name: markdown-link-check version
        run: npm list -g markdown-link-check
      - name: Run markdown-link-check on MD files
        run: find docs -name "*.md" | xargs -n 1 markdown-link-check -q -c .github/workflows/linkcheck.json
